update the porta-env

diff --git a/.rbenv/libexec/rbenv b/.rbenv/libexec/rbenv
--- a/.rbenv/libexec/rbenv
+++ b/.rbenv/libexec/rbenv
@@ -30,7 +30,12 @@ export RBENV_ROOT
 if [ -z "${RBENV_DIR}" ]; then
   RBENV_DIR="$(pwd)"
 else
-  RBENV_DIR="$(abs_dirname "$RBENV_DIR")"
+  cd "$RBENV_DIR" 2>/dev/null || {
+    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+    exit 1
+  } >&2
+  RBENV_DIR="$(pwd)"
+  cd "$OLDPWD"
 fi
 export RBENV_DIR
 
@@ -43,7 +48,7 @@ for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d"
+hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
 for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
@@ -55,7 +60,7 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "rbenv 0.2.1\n$(rbenv-help)" >&2
+  echo -e "rbenv 0.3.0\n$(rbenv-help)" >&2
   ;;
 * )
   command_path="$(command -v "rbenv-$command" || true)"
